#!/usr/bin/env python
from bottle import route, run, request

sessions = {}


def posthandler(action=None):
    global sessions
    print "Posthandler"
    if not action in sessions:
        print "Session reset %s" % action
        return gethandler(action)
    print sessions[action]
    return sessions[action].render(request.POST)


def gethandler(action=None):
    global sessions
    action = action or 'HOME'
    try:
        exec 'from ezdm_libs.ezdm_%s import %s as ActionSession' % (action.lower(), action.upper())
    except Exception as e:
        print "Failed to load %s: %s\nLoading default session" % (action, e)
        from ezdm_libs.frontend import Session as ActionSession
    if not action in sessions:
        sessions[action] = ActionSession()
    return sessions[action].render(None)


@route('/', method='get')
@route('/<action>', method='get')
@route('/<action>', method='post')
def main_page(action=None):
    global sessions
    if action == 'reset':
        action = None
        sessions = {}
    print request
    if request.POST:
        return posthandler(action)
    else:
        return gethandler(action)


if __name__ == '__main__':
    run(host='0.0.0.0', port=8000, reload=True)
