#!/usr/bin/env python
from ezdm_libs.util import load_json, smart_input, highlight, say
from ezdm_libs.character import Character,list_chars
import sys

def viewchar(myname):
    """View the character sheet for"""
    json = load_json('characters',myname)
    character=Character(json,True) 
    return character.pprint()   

if __name__ == '__main__': 
    highlight('EZDM - Character viewer')
    CLIST = list_chars()
    if len(CLIST) == 0:
        sys.exit()
    MYNAME=smart_input("Select Character to view",upper=True,validentries=CLIST.keys())    
    say(viewchar(CLIST[MYNAME]))

