#!/usr/bin/env python

import sys
import os
from simplejson import loads,dumps
from ezdm_libs.util import smart_input,load_json,json_from_template,highlight,say,rolldice
from ezdm_libs.character import Character,list_chars


if __name__=='__main__': 
    charlist=list_chars()
    basedir='characters'
    name=smart_input("Character trying",upper=True,validentries=charlist.keys())
    auto=smart_input('Use computer dice',validentries=['y','n']) == 'y'
    char=Character(load_json(basedir,charlist[name]),auto)
    ability=smart_input("Ability being tried",validentries=char.conditionals().keys())
    if char.tryability(ability):
        say("%s succeeded with %s" %(char.displayname(),ability))
    else:
        say("%s failed at %s" %(char.displayname(),ability))
