#!/usr/bin/env python

from ezdm_libs.util import option,load_json,smart_input,highlight,say,clearscr,gui
from ezdm_libs.character import Character,list_chars
from ezdm_libs.item import list_items,Item
import sys
import os

def view_inventory(character):
    
    output=[character.displayname(),'Items in pack:']
        
    for entry in character.list_inventory(['pack']):
        item=Item(load_json('items',entry))
        output.append('    %s' %item.displayname())
    output.append('')
    output.append('Items equiped:')
    for entry in character.list_inventory(['equiped']):
        item=Item(load_json('items',entry))
        output.append('    %s' %item.displayname())
    output.append('')
    output.append('Money:')
    output.append(character.list_money())
    return output

def select_item():
    itemlist=list_items()
    selection=smart_input("Select Item",validentries=itemlist.keys())
    return itemlist[selection]
    
def select_from_inventory(character,section=['pack','equiped']):
    itemlist={}
    for i in character.list_inventory([section]):
        item=Item(load_json('items',i))
        itemlist[item.displayname()]=i
    selected=smart_input('Select Item',validentries=itemlist.keys())
    return itemlist[selected]

def ask_money(action='add'):            
    gold=smart_input("Gold to %s" %action,default=0,integer=True)
    silver=smart_input("Silver to %s" %action,default=0,integer=True)
    copper=smart_input("Copper to %s" %action,default=0,integer=True)
    return {"gold":gold,"silver":silver,"copper":copper}

        

if __name__=='__main__': 
    PATH = os.path.dirname(sys.argv[0])
    highlight('EZDM - Inventory Manager')
    clist=list_chars()
    if len(clist) == 0:
        sys.exit()
    name=smart_input("Select Character",upper=True,validentries=clist.keys()) 
    print name   
    json=load_json('characters',clist[name])
    character=Character(json,True) 
    MESSAGE=""
    action=""
    while action.upper() != "QUIT":
        clearscr()
        if len(MESSAGE) >0:
            highlight(MESSAGE,sayit=True)
            say(['',''])
            MESSAGE=''
        say(view_inventory(character))
        actions=["Add item","Drop Item","Equip Item","Unequip Item","Create new item","Add money","Remove Money","Buy Item","Quit"]
        action=smart_input('Action',validentries=actions,upper=True)
        if action.upper() == "CREATE NEW ITEM":
            command="ezdm-mkitem"
            if not gui():
                command = command + ' --console'
            command=os.path.join(PATH,command)  
            os.system(command)
        if action.upper() == "ADD MONEY":
            money=ask_money()
            character.gain_money(money['gold'],money['silver'],money['copper'])
        if action.upper() == "REMOVE MONEY":
            money=ask_money('remove')
            if not character.spend_money(money['gold'],money['silver'],money['copper']):
                MESSAGE='Error: %s does not have enough money for that' %character.displayname()
        if action.upper() == "BUY ITEM":
            item=Item(load_json('items',select_item()))
            if not character.buy_item(item):
                MESSAGE='Error: %s cannot afford %s' %(character.displayname(),item.displayname())
        if action.upper() == 'ADD ITEM':
            item=Item(load_json('items',select_item()))
            character.acquire_item(item)
        if action.upper() == 'EQUIP ITEM':
            character.equip_item(select_from_inventory(character,'pack'))
        if action.upper() == 'UNEQUIP ITEM':
            character.unequip_item(select_from_inventory(character,'equiped'))
        if action.upper() == 'DROP ITEM':
            character.drop_item(select_from_inventory(character,'pack'))
            
    character.save()
        
