#!/usr/bin/env python
from ezdm_libs.util import rolldice,smart_input,dice_list,highlight


if __name__=='__main__': 
    highlight('EZDM - Dice Roller')
    numdice=smart_input('How many dice', integer=True,default=1)
    numsides=smart_input('What type',validentries=dice_list(),integer=True)
    modifier=smart_input('Modifier',integer=True,default=0)
    rolldice(True,numdice,numsides,modifier)

