#!/usr/bin/env python

import sys
import os
from simplejson import loads,dumps
from ezdm_libs.util import smart_input,load_json,json_from_template,highlight,say,rolldice,heal_dice
from ezdm_libs.character import Character,list_chars


if __name__=='__main__': 
    charlist=list_chars()
    basedir='characters'
    name=smart_input("Character trying",upper=True,validentries=charlist.keys())
    auto=smart_input('Use computer dice',validentries=['y','n']) == 'y'
    char=Character(load_json(basedir,charlist[name]),auto)
    dice=smart_input('Roll for healing',validentries=['y','n']) == 'y'
    if dice:
        char.heal(heal_dice(char.autoroll()))
    else:
        char.heal(smart_input('Heal by how much',integer=True,default=1))
