#!/usr/bin/env python
from gevent import monkey
monkey.patch_all()
from bottle import route, run, request, static_file
from ezdm_libs.util import load_icon, find_files, load_json
from ezdm_libs import get_sys_data
from ezdm_libs import frontend
from ezdm_libs.frontend import Page
from ezdm_libs.campaign import Campaign
import os

sessions = {}


def action_name(action):
    aname = '_' in action and action.upper().split('_')[1] or action.upper()
    return aname


def posthandler(action=None):
    global sessions
    print "Posthandler", sessions
    if not action_name(action) in sessions:
        print "Session reset %s" % action_name(action)
        return gethandler(action)
    print sessions[action_name(action)]
    return sessions[action_name(action)].render(request.POST)


def gethandler(action=None, item=None):
    global sessions
    print "GetHandler", sessions, action, item
    if frontend.mode == 'campaign' and frontend.campaign is None:
        page = Page()
        out = page.tplrender('header.tpl', {'title': 'Load Campaign'})
        campaigns = find_files('campaigns', '*.json', basename=True, strip=".json")
        campaigns = {'campaigns': campaigns}
        out += page.tplrender('load_campaign.tpl', campaigns)
        out += page.tplrender('footer.tpl', {})
        return out
    from ezdm_libs.frontend import Session as ActionSession
    action = action or 'ALL_HOME'
    to_import = 'from ezdm_libs.%s import %s as ActionSession' % (action.lower(), action_name(action))
    print to_import
    exec to_import
    if not action_name(action) in sessions:
        sessions[action_name(action)] = ActionSession()
    print sessions
    if not item:
        return sessions[action_name(action)].render(None)
    else:
        return sessions[action_name(action)].view(item)


@route('/load_campaign/<campaign>')
def load_campaign(campaign):
    frontend.campaign = Campaign(load_json('campaigns', campaign))
    return gethandler(None, None)


@route('/mode/<newmode>')
def setmode(newmode):
    frontend.mode = newmode
    return gethandler(None, None)


@route('/js', method='get')
def serve_js():
    filename = request.GET['path']
    return static_file(filename, root=get_sys_data('js'), mimetype='text/javascript')


@route('/icon/<source>/<filename>', method='get')
def icon(source, filename):
    icon = load_icon(os.path.join(source, filename))
    print "Serving %s" % icon
    extension = icon.split('.')[-1]
    return static_file(os.path.basename(icon), root=os.path.dirname(icon), mimetype='image/%s' % extension)


@route('/view/<action>/<item>', method='get')
def view(action, item):
    print "View %s %s" % (action, item)
    return gethandler(action, item)


@route('/reset', method='get')
@route('/reset/<action', method='get')
def reset(action=None):
    global sessions
    if not action:
        sessions = {}
    else:
        if action in sessions:
            del(sessions[action])
    return gethandler()


@route('/', method='get')
@route('/action/<action>', method='get')
@route('/action/<action>', method='post')
def main_page(action=None):
    global sessions
    print request
    if request.POST:
        return posthandler(action)
    else:
        return gethandler(action, None)


if __name__ == '__main__':
    run(host='0.0.0.0', port=8000, server='gevent')
