#!/usr/bin/env python
from ezdm_libs.util import option,load_json,smart_input,highlight,say
from ezdm_libs.character import Character,list_chars
import sys

def viewchar(name):
    json=load_json('characters',name)
    character=Character(json,True) 
    return character.pprint()   

if __name__=='__main__': 
    highlight('EZDM - Character viewer')
    clist=list_chars()
    if len(clist) == 0:
        sys.exit()
    name=smart_input("Select Character to view",upper=True,validentries=clist.keys())    
    say(viewchar(clist[name]))

