#!/usr/bin/env python
#First version limited automation
import sys
import os
from simplejson import loads,dumps
from util import smart_input,load_json,json_from_template,list_chars,highlight
from character import Character



save='n'
old = {}
while not 'y' in save.lower():
    highlight("EZDM - quick character sheet maker")
    template=load_json('adnd2e','template_cs')
    if len(old) == 0:
        basedir="characters"
        load=smart_input("Load defaults from existing sheet",validentries=["y","n"],default='y')
        if load == "y":
            name=smart_input("%s first name "%(basedir),upper=True,validentries=list_chars())
            filename="%s/%s.json" %(basedir,name)
            old=load_json(filename=filename)
            
    character=Character(json_from_template(template,old),True)
    character.json["combat"]["max_hp"]=character.json["combat"]["hitpoints"]
    highlight(character.displayname())
    character.pprint()
    save=smart_input("Save this %s ?" %(basedir.rstrip('s')),default="n",validentries=["y","n"],lower=True)
    if 'y' in save:
        character.save()
    else:
        old=character.get_json()
                
