#!/usr/bin/python
#First version limited automation
import sys
import os
from simplejson import loads,dumps

def input_default(default,msg):
	print "%s (%s)" %(msg,default) 
	i=raw_input()
	if i == '':
		return default
	else:
		return i

save='n'
default={"name":'',"hitdice":'',"armor_class":'',
			"str":'',"con":'',"dex":'',"int":'',"wis":'',"cha":'',
			"weapons":{"1":{"to_hit":"","type":"","dmg":""}},
			"atacks_per_round":"","parentclass":"warior","class":"fighter"}
while not 'y' in save.lower():
	print "EZDM - quick monster maker"
	monster={}
	monster["weapons"]={}
	monster["weapons"]["1"]={}
	monster['name']=input_default('',"Enter Monster name:" ).replace(' ','_')
	if os.path.exists('monsters/%s.json' %monster['name']):
		old=loads(open('monsters/%s.json' %monster['name'],'r').read())
	else:
		old=default
	for key in default.keys():
		if not old.has_key(key):
			old[key]=default[key]
	monster["parentclass"]=input_default(old["parentclass"],"Monster parent class ?")
	monster["class"]=input_default(old["class"],"Monster class ?")
	monster["hitdice"]=input_default(old["hitdice"],"How many hit dice ?")
	monster["armor_class"]=input_default(old["armor_class"],"Armor class ?")
	numweapons=int(input_default(1,"How many weapons ?"))
	for I in range(1,numweapons +1):
		monster["weapons"][str(I)]["to_hit"]=input_default(old["weapons"][str(I)]["to_hit"],"Enter weapon %s modifier to hit chance:" %I)
		monster["weapons"][str(I)]["dmg"]=input_default(old["weapons"][str(I)]["dmg"],"Enter weapon %s modifier to damage:" %I)
		monster["weapons"][str(I)]["type"]=input_default(old["weapons"][str(I)]["type"],'Enter monster weapon %s type: melee or misile' %I)
	monster["atacks_per_round"]=input_default(old["atacks_per_round"],"How many attacks does the monster get per round ?")
	print "Ability scores:"
	for ability in ["str","con","dex","int","wis","cha"]:
		monster[ability]=input_default(old[ability],"	%s" %ability)
	print "Recorded monster data: %s" % monster
	save=input_default('y',"Save monster y/n ?")
	if 'y' in save.lower():
		open('monsters/%s.json' %monster['name'],'w').write(dumps(monster,indent=4))
                
