#!/usr/bin/env python
import simplejson
from ezdm_libs.util import option,load_json
import sys
from pprint import pprint

if len(sys.argv) == 3:
        pprint (load_json(option(1),option(2)))
elif len(sys.argv) == 2:
        pprint (load_json(filename=option(1)))
else:
        print "Usage: test_json <source> <base>"
        print "       test_json <filename>"




