#!/usr/bin/python
import simplejson
from optparse import OptionParser
import sys

parser = OptionParser()
parser.add_option("--file",dest="filename",default=None,help="file to test")
(options, args) = parser.parse_args()

if not options.filename:
        print "Error: no filename specified"
        sys.exit(1)

DATA=open(options.filename,'r').read()
print "Raw data: %s" % DATA

JDATA=simplejson.loads(DATA)
print "JSON Data: %s" % JDATA


