#!/usr/bin/env python
from util import option,load_json,list_chars,smart_input,highlight
from character import Character

highlight('EZDM - Character viewer')
name=smart_input("Select Character to view",upper=True,validentries=list_chars())
json=load_json('characters',name)
character=Character(json,True)
character.pprint()
raw_input()
