#!/bin/bash -x
ln -sf /usr/games/ezdm* /usr/bin
cd /usr/games
for I in ezdm* ; do
	ln -sf $I ${I}.cgi
done
for I in /usr/lib/python2.7/dist-packages/ezdm_libs/*.py; do
        python -m compileall $I
done
update-desktop-database
#DEBHELPER#
